### ISSUE TITLE
Salt generation

### ISSUE THREAD

**Issue by prokne** [Miorey/trinitycore-srp6#1]
Hey. Thank you for this creator. I spent ours trying to do something similar. It appears that it would be much easier in PHP.
I am trying to implement your creator, but I cannot make it work. How do you generate the salt? I am using crypto.randomBytes(32) but it's now working. In fact I am able to write both salt and verifier to account DB, but I am not able to login (invaild password). So there must be something wrong with my implementation. Thanks for your help or any ideas.

**Comment by Miorey** [comment]
Hello @prokne on my server to create / modify user information I use directly the TrinityCore SOAP API it should work also for AzerothCore. Anyway I plan to add some unit test so I will have to generate salt / verifier.

**Comment by ihm-tswow** [comment]
I had no issues getting this to work with nodejs, but you have to use prepared statements to correctly write the binary parts. Also make sure you uppercase the username and password before you send them to the function. A brief example:

```ts
const srp = require('./SRP6')
const salt = Buffer.from(crypto.randomBytes(32));
const username = args[0].toUpperCase();
const password = args[1].toUpperCase();
const email = args[3] || ""
const verifier = (srp.computeVerifier(
      srp.params.trinitycore
    , salt
    , username
    , password
) as Buffer)

AuthServer.connection.queryPrepared(
      `INSERT INTO account (username,salt,verifier,reg_mail,email,joindate)`
    + ` VALUES (?,?,?,?,?,NOW());`
    , [username,salt,verifier,email,email]
)
```

Where my "queryPrepared" function is a wrapper for a mysql2 prepared statement: https://www.npmjs.com/package/mysql2#using-prepared-statements

**Comment by Miorey** [comment]
@ihm-tswow I think that the simplest way to create an account is to use the TrinityCore / AzertohCore SOAP  api, through SOAP client:
`.account create ${username} ${password} ${email}`
This have the following advantage:
- Avoid to block account creation in case of model evolution on core side.
- Security, this way you don't need `write` rights on `auth` DB.

**Comment by ihm-tswow** [comment]
For most cases, i'd agree! We use this to allow creating accounts on multi-realm configurations or from our console before the worldserver is running, although I think the best solution would be for cores to support soap through the authserver instead. Your SRP calculations seem correct and I haven't been able to break it (yet), with prepared statements it works like a charm.

**Comment by Miorey** [comment]
@ihm-tswow sadly in some rare (something between 1 and 5 %) cases the generated verifier is different from the one generated by c++. I think that is more a language problem due to the way that BigInts are managed.

**Comment by Miorey** [comment]
@prokne use @ihm-tswow  with SQL or mine with SOAP good luck !
